apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mavenwebappdp
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 20
  selector: 
    matchLabels: 
      app: mavenwebapp
  template:
    metadata: 
      name: mavenwebapp-pod
      labels: 
        app: mavenwebapp
    spec: 
      affinity:  
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - veera1
            topologyKey: "kubernetes.io/hostname"
      containers: 
      - name: mavenwebapp
        image: veeranjaneyulupagant/maven-web-app:1
        ports: 
        - containerPort: 8080
        readinessProbe: 
          httpGet: 
            path: /maven-web-application/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          httpGet: 
            path: /maven-web-application/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  selector: 
    app: mavenwebapp
  type: NodePort
  ports: 
  - port: 80
    targetPort: 8080
    nodePort: 31000

