apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdp
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: springapp
  template: 
    metadata: 
      name: spring-pod
      labels: 
        app: springapp
    spec:
      containers: 
      - name: spring-container
        image: veeranjaneyulupagant/spring-boot-mongo:1
        ports:
        - containerPort: 8080
        resources:
          requests: 
            cpu: "256m"
            memory: "512Mi"
          limits:
            cpu: "512m"
            memory: "1Gi"
---

apiVersion: v1
kind: Service
metadata:
  name: springsvc
spec: 
  type: NodePort
  selector: 
    app: springapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31001
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongopvc
spec:
   accessModes:
   - ReadWriteOnce
   resources:
     requests: 
       storage: "1Gi"


---

apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: mongodbrs
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mongoapp
  template: 
    metadata: 
      name: mongodbpod
      labels: 
        app: mongoapp
    spec: 
      volumes:
      - name: mongodbvol 
        persistentVolumeClaim: 
          claimName: mongopvc
      containers:
      - name: mongocontainer
        image: mongo
        ports: 
        - containerPort: 27017
        resources: 
          requests: 
            cpu: "200m"
            memory: "256Mi"
          limits: 
            cpu: "1"
            memory: "512Mi"
---

apiVersion: v1
kind: Service
metadata: 
  name: mongosvc
spec: 
  selector: 
    app: mongoapp
  ports:
  - port: 27017
    targetPort: 27017

